env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  accessor-pairs: error
  array-bracket-spacing: 'off'
  array-callback-return: error
  arrow-body-style: error
  arrow-parens: error
  arrow-spacing: error
  block-scoped-var: error
  block-spacing:
    - error
    - always
  brace-style: 'off'
  callback-return: 'off'
  camelcase: error
  comma-spacing:
    - error
    - after: true
      before: false
  comma-style:
    - error
    - last
  complexity: error
  computed-property-spacing: 'off'
  consistent-return: 'off'
  consistent-this: 'off'
  curly: 'off'
  default-case: 'off'
  dot-location: error
  dot-notation: error
  eol-last: error
  eqeqeq: error
  func-names: 'off'
  func-style: 'off'
  generator-star-spacing: error
  global-require: error
  guard-for-in: 'off'
  handle-callback-err: error
  id-blacklist: error
  id-length: 'off'
  id-match: error
  indent: 'off'
  init-declarations: 'off'
  jsx-quotes: error
  key-spacing: error
  keyword-spacing: 'off'
  linebreak-style:
    - error
    - unix
  lines-around-comment: error
  max-depth: error
  max-len: 'off'
  max-nested-callbacks: error
  max-params: 'off'
  max-statements: 'off'
  new-parens: error
  newline-after-var: 'off'
  newline-before-return: 'off'
  newline-per-chained-call: error
  no-alert: error
  no-array-constructor: error
  no-bitwise: error
  no-caller: error
  no-catch-shadow: error
  no-confusing-arrow: error
  no-continue: error
  no-console: 'off'
  no-div-regex: error
  no-else-return: 'off'
  no-empty-function: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: 'off'
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implicit-globals: 'off'
  no-implied-eval: error
  no-inline-comments: error
  no-inner-declarations:
    - error
    - functions
  no-invalid-this: error
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: 'off'
  no-loop-func: error
  no-magic-numbers: 'off'
  no-mixed-requires: error
  no-multi-spaces: 'off'
  no-multi-str: error
  no-multiple-empty-lines: error
  no-native-reassign: error
  no-negated-condition: error
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: 'off'
  no-path-concat: 'off'
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-process-env: error
  no-process-exit: error
  no-proto: error
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-modules: error
  no-restricted-syntax: error
  no-return-assign: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow: 'off'
  no-shadow-restricted-names: error
  no-spaced-func: error
  no-sync: error
  no-ternary: 'off'
  no-throw-literal: 'off'
  no-trailing-spaces: error
  no-undef-init: error
  no-undefined: error
  no-underscore-dangle: 'off'
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-use-before-define: 'off'
  no-useless-call: error
  no-useless-concat: error
  no-useless-constructor: error
  no-var: 'off'
  no-void: error
  no-warning-comments: error
  no-whitespace-before-property: error
  no-with: error
  object-curly-spacing: 'off'
  object-shorthand: 'off'
  one-var: 'off'
  one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak: error
  padded-blocks: 'off'
  prefer-arrow-callback: 'off'
  prefer-const: error
  prefer-reflect: 'off'
  prefer-rest-params: 'off'
  prefer-spread: error
  prefer-template: 'off'
  quote-props: 'off'
  quotes: 'off'
  radix: error
  require-jsdoc: 'off'
  require-yield: error
  semi: 'off'
  semi-spacing:
    - error
    - after: true
      before: false
  sort-imports: error
  sort-vars: 'off'
  space-before-blocks: 'off'
  space-before-function-paren: 'off'
  space-in-parens: 'off'
  space-infix-ops: 'off'
  space-unary-ops: error
  spaced-comment: 'off'
  strict:
    - error
    - never
  template-curly-spacing:
    - error
    - never
  valid-jsdoc: 'off'
  vars-on-top: 'off'
  wrap-regex: error
  yield-star-spacing: error
  yoda:
    - error
    - never
